<?php

namespace Tests\Unit\Jobs\Ava;

use Tests\TestCase;
use App\Jobs\Ava\ExportApplication;
use Illuminate\Support\Facades\Storage;

class ExportApplicationTest extends TestCase
{
    /** @test */
    public function it_exports_a_vacancy_application_to_pdf()
    {
        Storage::fake(config('vandango.ava.disk'));

        dispatch(new ExportApplication($this->application()));

        Storage::disk(config('vandango.ava.disk'))->assertExists('Ava/Applications/example-organisation-example-job-title-vac00123456789/John Doe - AVA000123456.pdf');
    }

    public function application()
    {
        return (object)[
            'id' => 123456,
            'applicant_id' => 25179,
            'vacancy_id' => 2428,
            'about' => '{"strengths":{"question":"What are your main strengths?","answer":"I have got a lot of experience for working well in a team and as an individual. When working for Grasmere Cleaners I had to work with others on certain aspects of a job to ensure that they got completed in a the time frame given. I also had to make sure I could mange all of my time given well to ensure all tasks got completed before the deadline. Whilst I work at Bojangles I have got to manage my time well so that all tasks get completed before the end of the shift to ensure that the next person working will not need to walk into an unfinished job. In both jobs I have had to work hard and ensure that everything I complete needs to be done to its very best so that it is fit for others to use. If I did not complete tasks to a good standard then it will obstruct others from being able to complete theirs as well as they could. Being able to work in both of these rolls also means that I have got good practical skills which allows me to complete a task within a deadline. when working as a pot washer I will sometimes have times when there is not as much equipment that needs to be washed. In these times I will go and complete a separate task and plan my time so that then I will not have times where I have a lot of work to do and times where I\'m standing around not doing much. from previous work experience I have had to ensure that all work has been completed with a large amount of attention to detail. this could include either checking of a pot of being washed to ensure that it is completely clean, or checking over a desk to make sure it hasn\'t got any cup marks. If I am able to work with a lot of attention to detail with a deadline as a team then this will mean that I should be a suitable candidate and possibly have a role in this apprenticeship and company."},"improvements":{"question":"What skills would you like to improve during this apprenticeship?","answer":"This apprenticeship would allow me to work a lot better in a team. At the moment I am able to work in a team when completing tasks however I think I am still able to develop when speaking my mind and ideas to others which could be useful and help the team complete a task which is necessary. Taking part in this apprenticeship would also allow me to be able to want to learn more and be willing to learn as sometimes I am able to complete a task set however when it comes to changing the way that it has been completed it is hard to use the new method if an older version has been completed multiple times. However this weakness can be developed whilst in the apprenticeship to ensure that I am able to quickly change and accept a different method."},"other_hobbies":{"question":"What are your hobbies and interests?","answer":"I personally enjoy building things and being active with my hands. This could include building 3-d puzzles or problems that need to be completed in order to complete a goal. I have not yet got any achievements or rewards for anything that would fit into this category for the apprenticeship, however my ambitions are to become some sort of engineer which could allow to earn an achievement."},"questions":[{"question":"How will you travel to work?","answer":"It is possible for me to travel to work in 3 possible ways. The first way that I can definitely get to work is riding a bike to and from the work place every day. My second option could be using the number 38 bus and get very close to the workplace and then walk the further distance. My third option would be to go in a car with a fellow employees and pay towards any fuel costs, however this option is more convenient but not necessary for me to get to work each day."},{"question":"Are you able to start this apprenticeship immediately?","answer":"I am still currently in school but am able to start as soon as I finish at the end of June."},{"question":"Do you have a learning difficulty, disability or health problem?","answer":"No"},{"question":"Is there anything we can do to support your interview?","answer":"I don\'t have any interview support requirements"}]}',
            'created_at' => '2018-05-10 08:05:02',
            'updated_at' => '2018-05-10 08:05:02',
            'deleted_at' => null,
            'applicant' => (object)[
                'id' => 25179,
                'first_name' => 'John',
                'surname' => 'Doe',
                'age_range' => null,
                'dob' => null,
                'email' => 'example@email.com',
                'tel' => '01234567890',
                'mob' => null,
                'created_at' => '2018-02-23 20:06:01',
                'updated_at' => '2018-02-23 20:06:01',
                'deleted_at' => null,
                'address' => [
                    (object)[
                        'id' => 46984,
                        'add1' => '49 Blythe Avenue',
                        'add2' => '',
                        'add3' => null,
                        'town' => 'Example Town',
                        'county' => 'Example County',
                        'post_code' => 'TS3 3ST',
                        'latitude' => '00.16358170',
                        'longitude' => '00.23727680',
                        'owner_id' => 25179,
                        'owner_type' => 'App\\Applicants\\Applicant',
                        'created_at' => '2018-02-23 20:06:01',
                        'updated_at' => '2018-02-23 20:06:20',
                        'deleted_at' => null,
                    ],
                ],
                'qualifications' => [
                    (object)[
                        'id' => 260051,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:01',
                        'updated_at' => '2018-02-23 20:06:01',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260052,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:01',
                        'updated_at' => '2018-02-23 20:06:01',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260053,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:01',
                        'updated_at' => '2018-02-23 20:06:01',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260054,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260055,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260056,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260057,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260058,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 260059,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271710,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:18',
                        'updated_at' => '2018-03-28 21:06:18',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271711,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:18',
                        'updated_at' => '2018-03-28 21:06:18',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271712,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:18',
                        'updated_at' => '2018-03-28 21:06:18',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271713,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271714,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271715,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271716,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271717,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271718,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271719,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:20',
                        'updated_at' => '2018-03-28 21:06:20',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271720,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:20',
                        'updated_at' => '2018-03-28 21:06:20',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271721,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:20',
                        'updated_at' => '2018-03-28 21:06:20',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271722,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:20',
                        'updated_at' => '2018-03-28 21:06:20',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271723,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271724,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271725,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271726,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271727,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271728,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:22',
                        'updated_at' => '2018-03-28 21:06:22',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271729,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:22',
                        'updated_at' => '2018-03-28 21:06:22',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271730,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:22',
                        'updated_at' => '2018-03-28 21:06:22',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271731,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:22',
                        'updated_at' => '2018-03-28 21:06:22',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271732,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:22',
                        'updated_at' => '2018-03-28 21:06:22',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271733,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271734,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271735,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 271736,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273847,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:05',
                        'updated_at' => '2018-04-06 15:05:05',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273848,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:05',
                        'updated_at' => '2018-04-06 15:05:05',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273849,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:05',
                        'updated_at' => '2018-04-06 15:05:05',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273850,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:05',
                        'updated_at' => '2018-04-06 15:05:05',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273851,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:05',
                        'updated_at' => '2018-04-06 15:05:05',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273852,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273853,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273854,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 273855,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277874,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Engineering',
                        'qualification' => 'BTEC',
                        'grade' => 'Distinction(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:10',
                        'updated_at' => '2018-04-18 21:05:10',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277875,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Computing',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:10',
                        'updated_at' => '2018-04-18 21:05:10',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277876,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'English',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:10',
                        'updated_at' => '2018-04-18 21:05:10',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277877,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'English Literature',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:10',
                        'updated_at' => '2018-04-18 21:05:10',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277878,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Mathematics',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277879,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Product Design',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277880,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'RE',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277881,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Science',
                        'qualification' => 'GCSE',
                        'grade' => '6(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 277882,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'subject' => 'Statistics',
                        'qualification' => 'GCSE',
                        'grade' => 'A(Predicted)',
                        'year' => 2018,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                ],
                'schools' => [
                    (object)[
                        'id' => 25776,
                        'applicant_id' => 25179,
                        'name' => 'Example High School High School',
                        'attended_from' => '2013',
                        'attended_to' => '2018',
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                ],
                'training' => [],
                'work_history' => [
                    (object)[
                        'id' => 79970,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 79971,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2189,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-02-23 20:06:02',
                        'updated_at' => '2018-02-23 20:06:02',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83860,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-03-28 21:06:19',
                        'updated_at' => '2018-03-28 21:06:19',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83861,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2325,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-03-28 21:06:20',
                        'updated_at' => '2018-03-28 21:06:20',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83862,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83863,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2317,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-03-28 21:06:21',
                        'updated_at' => '2018-03-28 21:06:21',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83864,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 83865,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2318,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-03-28 21:06:23',
                        'updated_at' => '2018-03-28 21:06:23',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 84603,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 84604,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2328,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-04-06 15:05:06',
                        'updated_at' => '2018-04-06 15:05:06',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 85859,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'organisation' => 'XYZ Ltd',
                        'title' => 'Part Time Cleaner',
                        'description' => 'Cleaning offices and buildings to a high standard within a deadline. This was sometimes done individually, however there was times when had to be completed in a team.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2017-02-01 00:00:00',
                        'worked_to' => '2017-05-01 00:00:00',
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                    (object)[
                        'id' => 85860,
                        'applicant_id' => 25179,
                        'vacancy_id' => 2428,
                        'organisation' => 'ABC Ltd',
                        'title' => 'Pot Washer',
                        'description' => 'Washing pots, pans and plates. The equipment had to be washed and put away as fast as possible so can be reused. Kitchen had to be cleaned at end of every shift so is ready for next shift.',
                        'is_apprenticeship' => null,
                        'is_voluntary' => null,
                        'worked_from' => '2018-08-01 00:00:00',
                        'worked_to' => null,
                        'created_at' => '2018-04-18 21:05:11',
                        'updated_at' => '2018-04-18 21:05:11',
                        'deleted_at' => null,
                    ],
                ],
            ],
            'vacancy' => (object)[
                'id' => 2428,
                'ref' => 'VAC00123456789',
                'title' => 'Example Job Title',
                'organisation_id' => 1338,
                'location_id' => 51464,
                'vacancy_count' => 0,
                'framework' => 'Construction Building',
                'wage' => 148,
                'working_week' => null,
                'closes_at' => '2018-06-22 00:00:00',
                'interviews_at' => null,
                'starts_at' => '2018-07-02',
                'status_id' => null,
                'created_at' => '2018-05-09 18:05:14',
                'updated_at' => '2018-05-10 08:05:02',
                'deleted_at' => null,
                'location' => (object)[
                    'id' => 51464,
                    'add1' => '1',
                    'add2' => null,
                    'add3' => null,
                    'town' => 'Macclesfield',
                    'county' => '',
                    'post_code' => 'SK11 7JX',
                    'latitude' => '53.25495690',
                    'longitude' => '-2.12223120',
                    'owner_id' => 1338,
                    'owner_type' => 'App\\Organisations\\Organisation',
                    'created_at' => '2018-05-09 18:05:14',
                    'updated_at' => '2018-05-09 18:05:38',
                    'deleted_at' => null,
                ],
                'organisation' => (object)[
                    'id' => 1338,
                    'name' => 'Example Organisation',
                    'email' => null,
                    'tel' => null,
                    'web' => null,
                    'twitter' => null,
                    'created_at' => '2018-05-09 18:05:14',
                    'updated_at' => '2018-05-09 18:05:14',
                    'deleted_at' => null,
                ],
            ],
        ];
    }
}
